### ISSUE TITLE
Comments on Project part 3

### ISSUE THREAD

**Issue by hamzaMAlvi** [CMPUT301F21T19/Habitappt#221]
# Comments and marks on project part 3. Please make issues with respect to comments if needed and link them with this issue.
Do not repeat the same mistakes again, noted by your TA during the meetings. Ask questions as early as possible. Use this issue for asking questions regarding comments etc.

****

### Comment: 
Good - it seems like half requirements are done but the code is a bit hard to follow because of a lack of comments. The are also confusing error messages when attempting to create an account (The app crashes if you don't have a user name but input a password on acocunt creation, and isn't clear you need letters and numbers for a password). The naming conventions are also inconsistent (usually Java is CamalCaseFor class names as opposed_to_using_underscores). 

### Comment:
Good - Some portions of the code are seemingly well documented with clear descriptions and other portions have none at all. 

### Comment:
Good work, made use of using sub tasks for larger stories.

### Comment:
More than one UI Tests fail (e.g. editHabitEvent, deleteHabitEvent, addHabit, removeHabit). Your Unit tests should be more comprehensive in testing model classes. Please remove commented tests or tests that are empty.

### Comment:
In code, divide classe into proper packages. UML classes cant be detached from the rest of the diagram. Layers, MVC, missing. Why can HabitList exist without Habits? USe camel case for class names. Class names cant be verbs, verbs are actions/methods/functions. Wrong identification of aggregations, all classes associated to Habits should be destroyed when a habit destroys. Profile keeps habits right? Then why is is detached. Location missing. Firebase Storage is na inappropriate class name a class name should exhibit its behaviour i.e., what it does. Worng notation for interface implementation used. Instead of udnerscores in class names, use camelCase. A weird unknown circle dot used within UML. UML needs reconstruction.

### Comment:
It seems like all comments were addressed and they were tracked.

### Comment:
Mostly Consistent and clear UI, stroyboard is clear. Need some improvements regarding the intuitiveness of the UI, It is too dense. Reflect the edits done in the app reflect on UI mockups and storyboard. I pointed somethings during the demo, reflect those in the mockups and storyboard as well.

### Comment:
There is some kind of sprint planning. They displays the understanding of scrum. Sprints are not planned by user stories, no priority planning in addressing user stories, No review of sprint shown. user stories are somewhat completed.

### Comment:
Comments and suggestions given on the spot should not be repeated. The organization of presented features should be improved. Prepare well before the demo time, and practice again and again.

### Comment:
You need to improve yourselves in using the tools. You still lack in following some standards.

### Comment:
Somewhat above average relative quality, overall comprehensiveness, creativity, attractiveness, and innovation

****
****

Issues:

- [x] #228
- [x] #229
- [x] #230
- [x] #231
- [x] #232

**Comment by Sohaib404** [comment]
@hamzaMAlvi 
We had our UI tests working for Part 3. Is there a chance a later version of our repo was used for Part 3 testing? This is our final Part 3 repo from Nov. 5th:
https://github.com/CMPUT301F21T19/Habitappt/tree/5d5347ba3630d23f5e7813b7f4563ad658136680

Also, we hadn't implemented our profile functionality for Part 3, that's why the classes were disconnected off to the side on our UML diagram.

Thanks!

**Comment by hamzaMAlvi** [comment]
> @hamzaMAlvi We had our UI tests working for Part 3. Is there a chance a later version of our repo was used for Part 3 testing? This is our final Part 3 repo from Nov. 5th: https://github.com/CMPUT301F21T19/Habitappt/tree/5d5347ba3630d23f5e7813b7f4563ad658136680
> 
> Also, we hadn't implemented our profile functionality for Part 3, that's why the classes were disconnected off to the side on our UML diagram.
> 
> Thanks!

I will ask the respective TA's, and convey their reply.
