### ISSUE TITLE
Comments on the Part 2 Submission

### ISSUE THREAD

**Issue by hamzaMAlvi** [CMPUT301F21T19/Habitappt#72]
These are the comments by other TA's on the project part 2 submission. You need to address these comments for your next submission.
If necessary make new issues relevant to the comments and link them to this issue (make them a subtask of this issue). If you have any confusion mention me in the comments section of this issue along with the question.

@Hamzahab @the-rooster @Sohaib404 @loganv90 @abrarhs @Aden-Adar 

- Good, There doesn't seem to be any discussion of requirements for any tasks beyond just the immediate way the user stories were originally written. You might want to think about how for each one you are defining it as being "done". I'd also recommend leveraging more of the available tools in GitHub. For instance, your story points and risk are all text. These might be better to be made into labels.

- For presentation, wrong CRC cards format. Classes that talk to the database are missing.

- Make UI more intuitive for users. Every requirement is covered and mockups are consistent.

- Good Job in using GitHub. Follow the standard practices for using different tools. Make sure everyone contributes to the project.

## Tasks
- [x] #80
- [x] #81
- [x] #82
- [x] #83

**Comment by hamzaMAlvi** [comment]
@Hamzahab @the-rooster @Sohaib404 @loganv90 @abrarhs @Aden-Adar 

Marks
Product Backlog: 2/3
OO Analysis: 2/3
UI MockUp & Storyboard: 3/3
Tool Practices: 1/1

**Comment by Sohaib404** [comment]
- We updated the CRC cards structure to look more like cards and added some more descriptive explanations. 
- Both our UI mockup and in app UI has been updated to be more user friendly.
- We started using tags for each US and added more subtasks within them to describe how each US requirement would be met.
