### ISSUE TITLE
Make UI look better

### ISSUE THREAD

**Issue by loganv90** [CMPUT301F21T19/Habitappt#81]
The UI does not look user friendly. So, we have to fix it.

## Tasks
- [x] #92
- [x] #86
- [x] #96
- [x] #87
- [x] #97
- [x] #84
- [x] #100
- [x] #99
- [x] #98
- [x] #90
- [x] Update UI mockup

**Comment by Sohaib404** [comment]
Finished updating UI elements for Project Part 3 & updated UI Mockup on Wiki page.
